### ISSUE TITLE
Views composed with `presenter.view = presenter.compose_at(...)` are permanantly cached

### ISSUE THREAD

**Issue by rjclardy** [pakyow/pakyow#106]
I have a page with a form that gets composed like so:

```ruby
      presenter.view = presenter.compose_at(
        'users/settings',
        template: 'consumer'
      )
```

It displays the form data properly the first time it's loaded, but on subsequent loads it displays the page as it was at the time of that first load. I can alter the data in the database and reload the page but it just displays the original data again (even after logging out and back in as a different user). Restarting the server is the only way I've found to get it to re-compose the view instead of using the cached version.

I'm not sure if the issue is a side-effect of using `presenter.view` or of using `presenter.compose_at`, but it works fine if I just set `presenter.path` instead. However, that doesn't work for cases where the template needs to be specified dynamically.

**Comment by bryanp** [comment]
@rjclardy So far I've been unable to reproduce in an isolated test case. You provide the code around composition, but not the data binding code. Can you provide a more complete example?

Also, is this in a development or production environment?

**Comment by bryanp** [comment]
This was related to some of the nested partial weirdness that is now resolved.
