### ISSUE TITLE
Scope Versions

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#107]
There has been a lot of prior conversation about handling multiple scope names that represent the same data (e.g. https://github.com/pakyow/pakyow/issues/81). I think we can handle this with the view version concept introduced in 0.10. Here's an example view:

``` html
<div data-scope="post" data-version="foo">
  foo
</div>

<div data-scope="post" data-version="bar">
  bar
</div>
```

Right now you can use view versions for a couple of things.
1. Present a single list of posts using one version or the other per post.

``` ruby
view.scope(:post).version(posts) do |view, post|
  # assumes post.type returns :foo or :bar
  view.use(post.type)
end
```
1. Present a single post using one particular version.

``` ruby
view.scope(:post).use(post.type)
```

However, if you want to render two lists of posts (one list for `foo` and one list for `bar`) you end up having to do something like this:

``` ruby
view.scope(:post)[0].apply(foo_posts)
view.scope(:post)[1].apply(bar_posts)
```

I have a lot of issues with this, not the least of which is that it's extremely brittle.

With a relatively small addition to `Pakyow::Presenter::ViewVersion` we could support this:

``` ruby
view.scope(:post, version: :foo).apply(foo_posts)
view.scope(:post, version: :bar).apply(bar_posts)
```

Thoughts? I'd particularly like to hear from @rjclardy on this one.

**Comment by rjclardy** [comment]
Only potential issue I see is that I don't know if it would handle scenarios where your page has a third `post` scope with a version of `baz` that needs to be handled differently than the other two versions. Maybe the `baz always want the `baz` version to be displayed but you want to use `scope(:post).use(post.type)` to choose either the `foo` or `bar` version. I can't think of a time we've ever needed to do that though.

Aside from that, I can't think of anything we could do with `data-alias` that we couldn't do with this approach.

**Comment by bryanp** [comment]
Good point. That's certainly a valid edge-case to consider; even without the proposed addition. One approach would be to add the ability to exclude versions, something like:

```ruby
view.scope(:post).version(posts, exclude: :baz) do |view, post|
  # assumes post.type returns :foo or :bar
  view.use(post.type)
end
```

Worth exploring?

**Comment by rjclardy** [comment]
Nice, yeah I like that.
