### ISSUE TITLE
Make it possible to disable presenter

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#112]
Currently, requiring the `pakyow-presenter` gem enables presenter and there's no way to disable it. I'd like to keep the auto-enable behavior but make it possible to disable. This presents a challenge as the `Pakyow::App` hooks [defined here](https://github.com/pakyow/pakyow/blob/master/pakyow-presenter/lib/presenter/presenter.rb) are registered when the gem is required.

Likely what we'll want to do is move presenter hook registration into an `after :configure` hook and check a config option to determine if presenter should be setup or not. I recommend adding a config option called `presenter.enabled`. It would default to `true` and could be overridden like this:

``` ruby
configure do
  presenter.enabled = false
end
```

**Comment by jphager2** [comment]
Here is an [updated link](https://github.com/pakyow/pakyow/blob/master/pakyow-presenter/lib/pakyow/presenter/presenter.rb#L29) to where the hooks in presenter are registered.

**Comment by bryanp** [comment]
Closing this in favor of #145.
