### ISSUE TITLE
Move app.log_output and app.log config options

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#115]
We have a configuration namespace for `logger` but two options (`log_output` and `log`) have leaked into `app`. I'd like to consolidate these under the `logger` namespace and rename them. Example usage:

```ruby
configure do
  # true by default; previously app.log_output
  logger.stdout = false

  # true by default; logger could also be disabled
  logger.enabled = false
end
```

**Comment by GuruKhalsa** [comment]
I've started working on this GuruKhalsa/pakyow@202f15c2763eb48b8b57318dfa924d8c872a416d (I initially forgot to rename the attributes so that's in a separate commit) but I was wondering what the best approach is to addressing the fact that the template's Gemfile references an older version of pakyow (~> 0.10) and this is a breaking change because of the modifications to the template's middleware/logger.rb file.  Should I just point the template's Gemfile to master or is there a better approach?  Thanks!

**Comment by bryanp** [comment]
Good question! To date, we've not bothered with this. If you're generating an app from the latest source instead of the latest gem install, you'll know to point the generated Gemfile to master for things to work. We'll update the generated Gemfile when releasing the next release (0.11 in this case). Thoughts?

**Comment by GuruKhalsa** [comment]
Thanks for the response!  I guess I'm curious what the drawbacks of updating it to point to master until the next release would be.  I'm having trouble coming up with them myself, and in my mind there seem to be benefits to keeping the branch in a working state, which would lead me to think that updating it might be a good idea.  What do you see as the downsides of pointing to master until the next release?  Thank you so much for taking the time to discuss it with me.

**Comment by bryanp** [comment]
The only drawback I can think of right now is that it's another thing to change prior to a release. I'd like to minimize those. That said, I see your point here and would like to find a solution. Since we now have the ability to generate the Gemfile with ERB, I wonder if we could generate the right version based on generation happening from an installed gem vs source. Maybe there's a way to detect?

**Comment by GuruKhalsa** [comment]
What about something like this: GuruKhalsa/Pakyow@f82e3b1ce167f2a7f18870098dfc2f7f9033d911
The one downside I've noticed is that Gem#latest_version_for doesn't seem to be very performant and slows down app generation a noticeable amount.
If it seems like it might work it would probably also be a good idea to pull the alternate version from the Gemfile so it isn't hard coded in there, but I just wanted to get your thoughts on the approach first.

**Comment by bryanp** [comment]
The version comparison code looks good, but I would put that code right into `templates/Gemfile`. Every file is evaluated as ERB, so we can do all sorts of nifty things 😀

You're right though, `latest_version_for` is *really* slow (6.4s on my side). That's not ideal. As an alternative, I propose using `$PROGRAM_NAME`. Here's the value when using`pakyow s`:

```
/Users/bryanp/.rbenv/versions/2.2.2/bin/pakyow
```

With `bundle exec pakyow s`:

```
/Users/bryanp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/pakyow
```

With the local executable:

```
/users/bryanp/code/pakyow/libs/pakyow/bin/pakyow
```

Checking if `$PROGRAM_NAME` includes `Gem.dir` should give us the answer.

Thoughts on this approach?

**Comment by GuruKhalsa** [comment]
Thank you so much for the response.  Ya after testing it a bit more I completely agree, latest_version_for is unusably slow and putting the logic directly in the Gemfile does make more sense.  
Apologies for my lack of understanding, but I'm struggling to grasp the approach.  In my mind the local executable would be run (pakyow new), the template files would be copied over to the user's local filesystem and the Gemfile code would be executed in that context so $PROGRAM_NAME would point to the local bundle executable and would always include Gem.dir.  Sorry if I'm missing something obvious.

**Comment by bryanp** [comment]
Nope, you're totally right. Apologies; my process is to generate with the local executable and also *run* the project with the same local executable (I have a `pakdev` alias, so `pakdev s` instead of `pakyow s`). However, it's certainly possible to generate locally and run with the bundled executable, and we want it to work properly in this case or risk confusing people.

There's gotta be another way to approach this.

**Comment by GuruKhalsa** [comment]
What if we take a step back and approach it as an issue of encapsulation.  If we were to have the pakyow template generator store the config values in a template config file then the generated pakyow app could reference those values internally with a standardized interface and any future changes to the implementation would be hidden from it.  Then we've got a potential solution to the config interface mismatch issue going forward and we could address the Gemfile version issue separately with a much simpler approach like taking the gem version preference as a command line argument.

**Comment by bryanp** [comment]
I'm on board with this. FYI the generator is being worked on as part of #108. That shouldn't present any major problems, but I wanted you to be aware. Thanks for thinking this through!
