### ISSUE TITLE
Respect all_views_visible configuration option

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#116]
There's a config option called `all_views_visible` that isn't being respected. Its intended use is to disable Pakyow's default behavior of serving views without a route behind them. There are a few aspects to this:

1. Move the config option out of the `app` namespace into `presenter`.
2. Give it a better name, such as `require_route`.
3. Add code to presenter that respects this config option.

I think it should default to `false` in development and `true` for production environments.

**Comment by jphager2** [comment]
https://github.com/pakyow/pakyow/pull/120
