### ISSUE TITLE
Website Hello World tweaks

### ISSUE THREAD

**Issue by dannagle** [pakyow/pakyow#121]
Some mild oddities I noticed when working the hello world located at:
https://pakyow.org/docs/start

### Download Ruby
- This page was not helpful. 
- I'm on Windows. There was no link to RubyInstaller
- Does anybody actually download and compile Ruby by hand? Linux has apt-get. Mac has Homebrew. Windows has RubyInstaller.
- I think direct links to the most helpful page for each OS would be best. 

### Download RubyGems 
- Link is 404'd. Correct link is not plural: https://rubygems.org/pages/download
- Perhaps note that RubyInstaller also makes gem available for windows users?

## Running the Server
- Needed to tell me to cd in to the project I just created.

**Comment by bryanp** [comment]
Thanks @dannagle! We'll correct these issues -- if you have the time and beat us to it, feel free to open a PR over on https://github.com/pakyow/docs. Would you also be interested in contributing some documentation for getting Ruby / Pakyow installed on a Windows system? We don't have a good resource for Windows at the moment. You could provide some much-needed info!

**Comment by dannagle** [comment]
Sure. No prob.

**Comment by karimmtarek** [comment]
shouldn't this be closed? :)

**Comment by bryanp** [comment]
Yup :)
