### ISSUE TITLE
Requests paths like "//about" aren't handled correctly

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#123]
Currently requests to paths such as "//about" raise a `MissingView` error. Instead, I believe the extra "/" should just be thrown out when dealing with the request path (in router and presenter). This seems consistent with behavior on other websites (e.g. https://www.google.com//intl/en/about/).

**Comment by iamvery** [comment]
I've certainly seen many services that respond in this manner (essentially suppressing the extra `/`). It's interesting to note that by the standard, `/about` and `//about` represent different paths. I like this approach http://webmasters.stackexchange.com/a/8381.

**Comment by bryanp** [comment]
Interesting. When I starting thinking about this I thought it made sense to 301 redirect. But then I started looking at other popular websites and I didn't find this behavior. Since the standard says `/about` and `//about` are different paths, it's probably best to do the thing that most respects the standard. Throwing that out for a moment, is there a compelling reason *not* to 301 redirect?

**Comment by iamvery** [comment]
I don't have a ton of experience to base it on, but I'd say stick with the standard. I don't think the 301 is a violation of the standard. It's more a shortcut/convenience. It's a better solution than just matching both URIs.

What do you think?

**Comment by karimmtarek** [comment]
@bryanp I started to look into this, do you want to handle it differently than you suggested on the description?

**Comment by bryanp** [comment]
@karimmtarek After sleeping on it, I think we should take the 301 redirect approach. When a request comes in to `//about`, we check if the path contains `//`. If it does, we replace `//` with `/` and issue a 301 redirect to the new path. Pakyow will handle it from there by either matching a route or issuing a 404.

This sort of screams Rack middleware. Could be setup something like:

```ruby
module Pakyow
  module Middleware
    class ReqPathNormalizer
      def initialize(app)
        @app = app
      end

      def call(env)
        # if env['PATH_INFO'] contains //
          # normalize the path and issue 301 redirect
        # else
          # continue on
          @app.call(env)
      end
    end
  end
end
```

This middleware could be used by the app like:

```ruby
Pakyow::App.define do
  middleware do |builder|
    builder.use Pakyow::Middleware::ReqPathNormalizer
  end
end
```

The generated app could ship with this middleware enabled by default.

We should be able to wrap the middleware object in unit tests pretty easily.

Does this help?

**Comment by karimmtarek** [comment]
@bryanp Sure it helps :+1: 
Though to know for sure I think still need to give it a shot and get back to you :)

**Comment by bryanp** [comment]
Great; let me know how I can help!

**Comment by karimmtarek** [comment]
@bryanp I created a PR for this, it's far from being functional, I just wanted a way to share the code and get some help :) 
If you can help me write proper specs, so I can code against it that would be great.

**Comment by bryanp** [comment]
@karimmtarek Nice progress! I hope to have some input on specs over the weekend 😀

**Comment by karimmtarek** [comment]
@bryanp thanks, that would be great though you can enjoy your weekend and get back to me next week :wink:

**Comment by bryanp** [comment]
:tada:
