### ISSUE TITLE
Transformations to partials that are included multiple times seem to be cached

### ISSUE THREAD

**Issue by rjclardy** [pakyow/pakyow#125]
If you have an `index.slim` like file so:
```slim
h3 Current
/! @include tile

h3 Previous
/! @include tile
```

With a `_tile.slim` partial:
```slim
div@@tile
  p@name
```

And you populate it with data like so:
```ruby
view.scope(:tile)[1].apply([
  { name: 'bar' },
  { name: 'bar2' }
])

view.scope(:tile)[0].apply([
  { name: 'foo' },
  { name: 'foo2' }
])

```

The resulting view will be correct on the first page load:
```html
<h3>Current</h3>

<div data-scope="tile">
  <p data-prop="name">foo</p>
</div>

<div data-scope="tile">
  <p data-prop="name">foo2</p>
</div>

<h3>Previous</h3>

<div data-scope="tile">
  <p data-prop="name">bar</p>
</div>

<div data-scope="tile">
  <p data-prop="name">bar2</p>
</div>
```

But if you refresh the page you'll get the output below. Notice that the Current section now has an extra set of data (`bar` and `bar2`):
```html
<h3>Current</h3>

<div data-scope="tile">
  <p data-prop="name">foo</p>
</div>

<div data-scope="tile">
  <p data-prop="name">foo2</p>
</div>

<div data-scope="tile">
  <p data-prop="name">bar</p>
</div>

<div data-scope="tile">
  <p data-prop="name">bar2</p>
</div>

<h3>Previous</h3>

<div data-scope="tile">
  <p data-prop="name">bar</p>
</div>

<div data-scope="tile">
  <p data-prop="name">bar2</p>
</div>
```

Each time you refresh the page another set of data will be added to the Current section. If you print out the result of `view.scope(:tile).html` on subsequent loads _before_ you ever attempt to bind the data, you'll notice that the view is still populated with the data from the previous request, which is what causes it to keep growing (in this case).

However, if you copy the markup from `_tile.slim` and paste it directly into `index.slim` instead of loading it via `@include`, the data will be displayed correctly every time you refresh the page. So it seems like there's a flow that allows view transformations to be applied to partials without dupping them first.

Another oddity though is that if you only include the partial once instead of twice (and remove the view logic responsible for populating the second instance), the data is displayed correctly on every reload. So it seems like the sad path probably goes through `ViewCollection` at some point.

**Comment by bryanp** [comment]
I believe this is fixed by this commit: https://github.com/pakyow/pakyow/commit/bdddd1bf94059ef616fc31dac080d9ae525384bd

Can you confirm?

**Comment by rjclardy** [comment]
Confirmed :100:
