### ISSUE TITLE
Restructure CLI app generator to use Thor as a generator

### ISSUE THREAD

**Issue by iamvery** [pakyow/pakyow#133]
After #129, we have access to Thor which also has the ability to generate files. It might be desirable to use this rather than Pakyow's hand-rolled app generation (esp. since we already have a dependency on Thor).

**Comment by yodarunamok** [comment]
@bryanp should I branch off master for this one?

**Comment by bryanp** [comment]
@yodarunamok since it's part of the 1.0 track, go ahead and branch off `environment`
