### ISSUE TITLE
Puma error when change default route on Pakyow warmup tutorial

### ISSUE THREAD

**Issue by karimmtarek** [pakyow/pakyow#137]
While working though the warmup tutorial, I got this error:
```
Puma caught this error: No such file or directory @ rb_sysopen - /Users/karim/.rvm/gems/ruby-2.3.0/gems/pakyow-presenter-0.10.2/pakyow-core/lib/views/errors/500.html (Errno::ENOENT)
```
The app was working fine until I replced the default route with
```
default do
    # increment the counter
    data(:stats).view_default_post

    # render the stats
    view.scope(:stats).mutate(:post,
      with: data(:stats).for_default_post
    ).subscribe
end
```
For refrence, my code can be found [here](https://github.com/karimmtarek/pakyow-warmup)

Reverting to the old route, which is:
```
default do
    logger.info 'hello'
end
```
Fixes the problem, though that won't be very helpful :)
Is this a bug, or I might of missed something up?

**Comment by bryanp** [comment]
It's a bug that has been fixed since the 0.10.2 release (see https://github.com/pakyow/pakyow/commit/ce7b1eedfbc92846a4a18fc61c58360bcd3cfd7d). Since it will be included in the next release, I'll go ahead and close this out. Please reopen if you have any further questions or comments.

**Comment by karimmtarek** [comment]
In this case how can I get this fix? should I change the Pakyow version in the Gemfile? Please advice, thanks :)

**Comment by bryanp** [comment]
Until the next release is out, your only option is to point to `master`. I considered making a 0.10.3 release that includes this fix only, but that's not very straight-forward. So, we need to kick 0.11 out the door. It's possible that could happen this week, but there are a few things that need to be completed first.

A catch to pointing a 0.10.2 generated app at master is that middleware isn't loaded by default. Add this to the `middleware` block in your project's `app/setup.rb`:

```ruby
builder.use Pakyow::Middleware::Logger if Pakyow::Config.app.log
builder.use Rack::MethodOverride
builder.use Pakyow::Middleware::Reloader if Pakyow::Config.app.auto_reload
builder.use Rack::Session::Cookie, key: "#{Pakyow::Config.app.name}.session", secret: ENV['SESSION_SECRET']
builder.use Pakyow::Middleware::Static if Pakyow::Config.app.static
```

Hit us up on [Gitter](https://gitter.im/pakyow/chat) with issues related to running off `master`.

**Comment by karimmtarek** [comment]
:+1:
