### ISSUE TITLE
Create a new `WWWEnforcer` middleware

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#138]
The apps I deploy are setup to 301 redirect requests for `www.mydomain.com/*` to `mydomain.com/*`. I've seen some Rack middleware that does this but it's not well maintained. Since this is something that I do personally for every app (and presumably would be useful to the community), I'd like to create our own middleware that solves this problem.

Ideally a config option would be available to let a developer decide if they want to enforce www or non-www (non-www by default please). The middleware would be pretty simple:

1. Check if the host starts with `www`.
2. If it does *and* we are enforcing non-www, 301 redirect to the non-www version (do the opposite if we're enforcing www).
3. If it's right just pass the request through.

If you're new to Rack middleware you can take a look at the [ReqPathNormalizer](https://github.com/pakyow/pakyow/blob/master/pakyow-core/lib/core/middleware/req_path_normalizer.rb) for inspiration.

**Comment by bryanp** [comment]
Since forever I've fallen in the non-www camp, but recently found this via Ilya Grigorik: http://www.yes-www.org/why-use-www/. It's making me rethink what the default should be in Pakyow. Chime in if you have an opinion!

**Comment by yodarunamok** [comment]
I'm in the pro-www camp.  And I mostly agree with the article, though I **do** think there are some edge cases where you don't want a site to get too big.

**Comment by karimmtarek** [comment]
@bryanp is this still a go?

**Comment by bryanp** [comment]
@karimmtarek Yes, it sure is. Let's enforce www by default, but allow it to be configured for non-www. We should be careful to not step on subdomains (e.g. `foo.pakyow.com` shouldn't be enforced as `www.foo.pakyow.com`) 😄

**Comment by karimmtarek** [comment]
Sounds good, I'll start looking into it.
