### ISSUE TITLE
Create a new `SSLEnforcer` middleware

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#139]
Most apps that are setup to use https should use it all of the time. Configuring nginx, etc to force ssl is hard, so let's make it easier with built-in middleware. A config option would be available to let a developer decide if they want to enforce https or http (http by default).

If you're new to Rack middleware you can take a look at the [ReqPathNormalizer](https://github.com/pakyow/pakyow/blob/master/pakyow-core/lib/core/middleware/req_path_normalizer.rb) for inspiration.

**Comment by jphager2** [comment]
Here's an updated link to [ReqPathNormalizer](https://github.com/pakyow/pakyow/blob/master/pakyow-core/lib/pakyow/core/middleware/req_path_normalizer.rb)

**Comment by danielpclark** [comment]
I'm guessing the normalizer is now here: [lib/pakyow/middleware/normalizer.rb](https://github.com/pakyow/pakyow/blob/master/lib/pakyow/middleware/normalizer.rb) and the refinement it's using is here: [pakyow-support/lib/pakyow/support/core_refinements/string/normalization.rb](https://github.com/pakyow/pakyow/blob/master/pakyow-support/lib/pakyow/support/core_refinements/string/normalization.rb)

**Comment by bryanp** [comment]
@danielpclark correct. I think the best path forward now is to add ssl enforcement to the normalizer middleware.

**Comment by danielpclark** [comment]
When you say a config option, is there something akin to a YAML file or the Rails config directory that this normalizer would refer to for that enforcement option?

I'm asking as I've not used Pakyow but have been a fan of the idea of it ever since I saw a presentation on it on Youtube.

**Comment by danielpclark** [comment]
According to the docs I've found I'm guessing `app/setup.rb` is the config file.

**Comment by bryanp** [comment]
Normalization happens at the environment level so that it applies across all apps running in the environment (there's one environment in a pakyow process, but it can run multiple apps). So the normalization config option would be [defined in environment](https://github.com/pakyow/pakyow/blob/9fcfcf50cf81c2fcf74adde5cf1da00e18b9da24/lib/pakyow/environment.rb#L169). 

The end-user would set the option in `config/environment.rb` (when this issue was created it was `app/setup.rb` but that has changed for v1.0). It would look something like this:

```ruby
Pakyow.configure do
  config.normalizer.require_https = true
end
```
