### ISSUE TITLE
Remove trailing `/` in request path

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#144]
I'd like to extend the middleware created in #123 to remove `/` in the request path. For example, requests to `/about/` would be 301 redirected to `/about`. This is pedantic, but it's something I've noticed many sites (including Google) doing. Unsure if it has any impact on search engines, but it can't hurt right?

**Comment by karimmtarek** [comment]
I'll pick this one up :)

**Comment by bryanp** [comment]
I thought you might!
