### ISSUE TITLE
Mailer views don't have access to app context

### ISSUE THREAD

**Issue by rjclardy** [pakyow/pakyow#149]
Currently mailer views don't have access to the app context and therefor you can't use certain functionality such as mutators. This isn't really an issue as much as a potential inconsistency that might should be resolved. It would be quite convenient to be able to use your existing mutators in both mail and non-mail views, so I wanted to capture this here for further discussion.

**Comment by bryanp** [comment]
Agreed. This is probably an oversight, so I've labeled as a bug.

**Comment by bryanp** [comment]
@rjclardy Can you point me to some code that shows how you were invoking a mutator on a mailer view?

**Comment by rjclardy** [comment]
I originally tried something like this, just like you'd do with a normal view, but it didn't work (let me know if you need the specific error and I'll try to reproduce):

```ruby
        m.view.scope(:offer).mutate(:details, with: { offer: offer })
```

I was able to make it work by doing this:

```ruby
        mailer_view = Pakyow::Presenter::ViewContext.new(m.view, self)
        mailer_view.scope(:offer).mutate(:details, with: { offer: offer })
```
