### ISSUE TITLE
Environment-specific `configure` blocks are running before the global `configure` block

### ISSUE THREAD

**Issue by rjclardy** [pakyow/pakyow#152]
We might have done this on purpose at one point, but there are a couple of side-effects from having environment-specific `configure` blocks run before the global `configure` block that are probably worth discussing:

- Environment-specific configs can be overridden by the global config, while the opposite is probably preferred/expected.
- Your environment-specific `configure` blocks can't depend on anything that's only setup in the global block (e.g. database connection, dotenv, require statements, etc.)

**Comment by bryanp** [comment]
Yeah, we should address this in the upcoming 0.11 release. Should be really easy.
