### ISSUE TITLE
app/lib should be in load path

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#153]
I've seen a couple reports of load path weirdness. Let's make sure that `app/lib` (or more specifically the value of `Pakyow::Config.app.src_dir`) is present in the load path when the app is prepared.

**Comment by iamvery** [comment]
Fwiw, I believe there are other load path issues in Pakyow. I'm not sure if they're really documented anywhere. It's generally good practice to namespace all files in a rubygem. For e.g. the pakyow version file is in `./lib/` (https://github.com/pakyow/pakyow/blob/master/lib/version.rb) which means it competes with any gem containing a file in lib with the name "version".

```
● master ~/Code/OSS/pinster-pakyow » gem list pakyow

*** LOCAL GEMS ***

pakyow (0.10.2)
pakyow-core (0.10.2)
pakyow-mailer (0.10.2)
pakyow-presenter (0.10.2)
pakyow-rake (0.10.2)
pakyow-realtime (0.10.2)
pakyow-support (0.10.2)
pakyow-test (0.10.2)
pakyow-ui (0.10.2)
● master ~/Code/OSS/pinster-pakyow » irb
irb(main):001:0> require "version"
=> true
irb(main):002:0> Pakyow::VERSION
=> "0.10.2"
irb(main):003:0>
```

**Comment by bryanp** [comment]
You're right. Created an issue to capture that.

Related to this, I'd like to change the organization of the code so that you can require a specific part of the pakyow framework like `require 'pakyow/core'` rather than `require 'pakyow-core'`. Thoughts?

Also, have you noticed any other load path related issues? If so I'd like to document them.

**Comment by iamvery** [comment]
The least surprising organization tactic i've seen goes something like this:

1. put all code in some namespace, e.g. `./lib/pakyow/`
1. have a file with the gem name in ./lib/, e.g. `./lib/packyow-core.rb`
  * this file might just load stuff from ./lib/[namespace]`

So if you wanted to load all of pakyow-core you'd just `require "pakyow-core"`. If there was some `AwesomeFeature` defined by pakyow-core and you wanted just that, you might `require "pakyow/awesome_feature"`. Or maybe it's very core-specifc `require "pakyow/core/awesome_feature"`.

With that style, it's OK for each of the pakyow gems to share the `pakyow/` namespace as long as you're careful not to clobber things between them.

Does all that make sense?

**Comment by bryanp** [comment]
Yep, it all makes sense. We have a bit of work to do but can straighten that out. Updated #159 to include this info and added it to the 0.11 milestone. Trying to get 0.11 out this week, so this should all be resolved soon :grin:

**Comment by iamvery** [comment]
Awesome! I may be able to take a shot at the load path stuff later this evening if you'd like.

**Comment by bryanp** [comment]
Sure, go for it! It'll be Thursday before I have a chance to jump in.

**Comment by iamvery** [comment]
:+1:
