### ISSUE TITLE
Need a better default log format

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#163]
The default log format wasn't really thought out. I'd like to intentionally think about what the format should be and make it so. Bonus points for making it easy to support alternative formats :-)

**Comment by brandon-beacher** [comment]
How about Heroku's `logfmt`?

https://blog.codeship.com/logfmt-a-log-format-thats-easy-to-read-and-write/

https://github.com/brandur/hutils

https://github.com/cyberdelia/logfmt-ruby

**Comment by bryanp** [comment]
@brandon-beacher Not opposed to it, but I don't find logfmt all that readable when doing local development. Here's what emerged over the last couple days of tinkering:

```
  0.04ms http.66049dd2 | GET / (for 127.0.0.1 at 2016-05-23 11:48:41 -0500)
  3.21ms http.66049dd2 | 200 (OK)
  0.03ms http.e7f40a16 | GET / (for 127.0.0.1 at 2016-05-23 11:48:42 -0500)
  0.01ms sock.ed8726f1 | client established connection
120.84ms http.e7f40a16 | 200 (OK)
```

This would be the log format in `development` mode *only*. Production logs could be outputted as `json` or `logfmt`; honestly it doesn't matter to me all that much. Here's a `json` example:

```
{"severity":"INFO","timestamp":"2016-05-23 11:52:18 -0500","type":"http","id":"cfbf38d6","elapsed":"0.01ms","method":"GET","path":"/","ip":"127.0.0.1"}
{"severity":"INFO","timestamp":"2016-05-23 11:52:18 -0500","type":"http","id":"cfbf38d6","elapsed":"2.82ms","status":200}
{"severity":"INFO","timestamp":"2016-05-23 11:52:18 -0500","type":"http","id":"50115e8f","elapsed":"0.01ms","method":"GET","path":"/","ip":"127.0.0.1"}
{"severity":"INFO","timestamp":"2016-05-23 11:52:18 -0500","type":"sock","id":"37b81a24","elapsed":"0.01ms","message":"client established connection"}
{"severity":"INFO","timestamp":"2016-05-23 11:52:18 -0500","type":"http","id":"50115e8f","elapsed":"3.21ms","status":200}
```

Thanks for your suggestion. Let me know if you have any thoughts on the above.

**Comment by brandon-beacher** [comment]
Logrus does a nice job of addressing the human readability disadvantage of `logfmt` by using conventions for the `info` and `msg` properties which are displayed differently in development when attached to a TTY:

https://github.com/Sirupsen/logrus

**Comment by bryanp** [comment]
@brandon-beacher It isn't just `level` and `msg` that present a readability problem, IMO. I guess my real question is what advantage does `logfmt` bring to a development environment? It makes sense in production, but I don't see the point of it when developing locally. Buy maybe you're only suggesting using `logfmt` in a production environment. Can you clarify?

**Comment by brandon-beacher** [comment]
Correct - notice how Logrus in development still shows the key=value pairs but drops the JSON noise.

I also was not thinking of this from your perspective: "How should Pakyow present logs to users of the framework."

Instead I was thinking of it from my perspective: "How do I present logs from my Pakyow application to myself."

**Comment by bryanp** [comment]
@brandon-beacher Thanks a bunch for your input. I see where you're coming from now. After thinking a bit more I am fine with Pakyow shipping with `json` or `logfmt` logs in production environments; not sure yet if i have a preference. In dev, I'd like to see something closer to what I proposed earlier today.

**Comment by karimmtarek** [comment]
I don't have much experience with formatting logs, though from the examples above, `logfmt` looks pretty good to me, much better than `json` format IMO.

@bryanp [this](https://pooreffort.com/blog/better-rails-logging/) might give you some ideas, I bookmarked it while back but never had the chance to read it 😄
