### ISSUE TITLE
Refactor `console` command to support IRB alternatives (like Pry).

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#173]
The design of the `console` command makes it hard to use something other than IRB. Instead of hardcoding, move the console object into a config option and default to `IRB`. Using `Pry` would be as easy as overriding the config option.

**Comment by Ch4s3** [comment]
I'll take a look.

**Comment by karimmtarek** [comment]
Hey @Ch4s3 any updates on this?

**Comment by bryanp** [comment]
implemented in https://github.com/pakyow/pakyow/commit/dbf6e2a7aa3d09aa385214e7eabca4844700210f
