### ISSUE TITLE
Documentation of pakyow-css

### ISSUE THREAD

**Issue by kofno** [pakyow/pakyow#174]
Is there documentation anywhere of the CSS that ships with Pakyow?

**Comment by bryanp** [comment]
@kofno Not at the moment. The [examples](https://github.com/pakyow/css/tree/master/examples) should get you going the right direction.

**Comment by karimmtarek** [comment]
@bryanp Is this going to be an actionable task/issue? If not, any value of keeping this open?

**Comment by bryanp** [comment]
@karimmtarek Yes, this is actionable. Just low-priority :)
