### ISSUE TITLE
Ensure that class attribute values are arrays

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#177]
Pakyow currently lets you do this:

``` ruby
view.attrs.class = 'foo'
```

This can cause problems down the line (e.g. https://github.com/pakyow/ring/pull/8) because the class attribute is expected to be an array of values. We should still allow this, but should make sure it's an array before replacing the current value.

**Comment by karimmtarek** [comment]
@bryanp what needs to be done here?

**Comment by bryanp** [comment]
@karimmtarek The problem is with `Pakyow::UI::UIAttrs`. It blindly accepts input rather that sanitizing values based on attribute type, per `Pakyow::Presenter::Attribute`. I put some thought into avoiding duplicate logic between the classes but didn't come up with a solid approach.

**Comment by karimmtarek** [comment]
@bryanp Do you have something actionable that I can start working on? Or this still needs some more thinking?

**Comment by bryanp** [comment]
It's actionable in that we need to figure out how best to replicate the `Presenter::Attribute` functionality in `UIAttrs`. If you're up for that, I'd say go for it. Otherwise it can happen as part of some of the larger Presenter changes that will occur in a few more weeks.

**Comment by karimmtarek** [comment]
Alright I'll look into it and get back with some code or questions :)

**Comment by karimmtarek** [comment]
Unfortunately I'm going to skip this one, sorry :(
