### ISSUE TITLE
Strange Behavior with Resources

### ISSUE THREAD

**Issue by jphager2** [pakyow/pakyow#181]
There seems to be a bug somewhere with `Pakyow::App.resource`.  If you create a resource (in routes.rb in this case), bindings will fail to work. Only after (in development mode) the bindings.rb file is saved (and thus reloaded) are the binding definitions respected.

Here is some code [(example repository)](https://github.com/jphager2/pakyow-resource-bug):

## app/views/index.html

```html
<div data-scope="user">
  <dt>Name: </dt>
  <dd data-prop="name">Joe</dd>
  <dt>Phone: </dt>
  <dd data-prop="phone">(+420) 700 000 000</dd>
</div>
```

## app/lib/routes.rb

```ruby
Pakyow::App.routes do
  default do
    view.scope(:user).bind({ name: "John", phone: "(+420) 607 079 803" })
  end

  # define application routes here
end

Pakyow::App.resource :anything, '/anything' do
end
```

## app/lib/bindings.rb

```ruby
Pakyow::App.bindings do
  # define bindings here

  scope :user do
    binding :name do
      part :content do
        if bindable[:name] == "John"
          bindable[:name] + ", so modest..."
        else
          bindable[:name]
        end
      end
    end
  end
end
```

## Generated HTML after starting server

```html
<div data-scope="user">
  <dt>Name: </dt>
  <dd data-prop="name">John</dd>
  <dt>Phone: </dt>
  <dd data-prop="phone">(+420) 607 079 803</dd>
</div>
```

## Generated HTML after saving (reloading) `bindings.rb`

```html
<div data-scope="user">
  <dt>Name: </dt>
  <dd data-prop="name">John, so modest...</dd>
  <dt>Phone: </dt>
  <dd data-prop="phone">(+420) 607 079 803</dd>
</div>
```

**Comment by jphager2** [comment]
Looks like there is a conflict in the bindings `set_name`. I think a good solution would be to use the scope set_name as the bindings set_name as well.

[This line](https://github.com/pakyow/pakyow/blob/master/pakyow-presenter/lib/pakyow/presenter/ext/app.rb#L5) would simply become:

```ruby
app.bindings(set_name) { scope(set_name) { restful(set_name) } }
```

**Comment by jphager2** [comment]
A quick fix for Pakyow 0.11.1 applications is to add a set_name other than :main to their bindings.rb file.

```ruby
Pakyow::App.bindings :other do
   # define bindings here
end
```

**Comment by bryanp** [comment]
Good catch @jphager2. We're drastically simplifying sets for 1.0 but this fix is needed in the meantime. Do you mind opening a PR? Target the `stable` branch and we'll include it in a 0.11.2 release.

**Comment by bryanp** [comment]
Thanks! 0.11.2 goes out Wednesday Jun 22 and will include this fix.
