### ISSUE TITLE
When creating a new pakyow project, the final success message is the same, even if there's an error of some sort.

### ISSUE THREAD

**Issue by yodarunamok** [pakyow/pakyow#203]
I noted this last weekend when creating a new Pakyow project. Running under Mac OS X, I hadn't yet launched an updated version of XCode, which resulted in an error related to not having accepted the license. However, Pakyow still displayed the same final success message (even though some gems were not completely installed.)

Here is the error output (note the unchanged message from Pakyow at the end):

```
creating Makefile
current directory: /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/oga-2.7/ext/c
make "DESTDIR=" clean
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
current directory: /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/oga-2.7/ext/c
make "DESTDIR="
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
make failed, exit code 69
Gem files will remain installed in /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/oga-2.7 for inspection.
Results logged to /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/oga-2.7/gem_make.out
An error occurred while installing oga (2.7), and Bundler cannot continue.
Make sure that `gem install oga -v '2.7'` succeeds before bundling.
Done! Run `cd projectName; bundle exec pakyow server` to get started!
```

**Comment by bryanp** [comment]
Thanks for reporting. We probably need to explicitly check the exit code of running `bundle install` during the setup process. This might be handled for us when we move project generation to Thor (#133) but we'll leave this open just in case.
