### ISSUE TITLE
Jekyll is rendering out front matter in docs

### ISSUE THREAD

**Issue by tugboat** [pakyow/pakyow#215]
I am spitballing here, but I think that Jekyll is rendering the front matter in code examples in the docs.  I couldn't find some info about templates and looking at the uncompiled docs in the repo shows it's there.

Here's an example:
<img width="747" alt="screenshot 2017-01-31 13 25 32" src="https://cloud.githubusercontent.com/assets/41271/22480935/c785170e-e7b8-11e6-9cea-399d311938ee.png">

In the actual repo it looks like this:
<img width="981" alt="screenshot 2017-01-31 13 27 04" src="https://cloud.githubusercontent.com/assets/41271/22481002/11a03de6-e7b9-11e6-9629-3f98893790d6.png">

The file is at https://github.com/pakyow/pakyow/blob/master/docs/presentation/_overview.md
I think it is github pages doing something weird when it compiles the docs.  I started googling for some info about how to get Jekyll to ignore parts of a view, but didn't have any luck.

I needed to move on to something else, so I'm adding this issue so we'll remember to go back and look at it in the future.

**Comment by bryanp** [comment]
Ah, yeah we are definitely losing something in the compilation. We aren't using Jekyll though, so this would be something in Pakyow itself. Recently we changed it to only match front-matter at the start of the view (https://github.com/pakyow/pakyow/commit/3c6ebf017fc71fc0319b7746cb4f76688cd6b522) so it may be that `pakyow-web` just needs to be pointed at the latest.

**Comment by tugboat** [comment]
Oh man, it would be sweet if that's all it took to get it working.  I thought that GH auto compiled stuff in docs to github pages and we were using that for the docs page.  If it's actually using pakyow that could definitely be it.

**Comment by bryanp** [comment]
🎉 https://github.com/pakyow/pakyow/issues/215
