### ISSUE TITLE
Output from "pakyow help server" incorrect

### ISSUE THREAD

**Issue by yodarunamok** [pakyow/pakyow#217]
Just looking for the output from `pakyow help server` it seems incorrect. Shouldn't the output for usage look like so:
```
Usage:
  pakyow server ENVIRONMENT [options]
```
Also, the options lists `p`, whereas the example shows `-p`.

**Comment by bryanp** [comment]
Yep, I think that's a good improvement. Take a look at [cli.rb](https://github.com/pakyow/pakyow/blob/environment/lib/pakyow/cli.rb) (in the `environment` branch) for the very latest. Can you branch from `environment` and improve to your liking?

**Comment by yodarunamok** [comment]
Yep, I can do that. Should I do the change from `p` to `-p`, too, or is that another item?

**Comment by bryanp** [comment]
Sure, go ahead!
