### ISSUE TITLE
Create DeepFreeze refinement for use in definables

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#253]
The `Definable` module freezes the object once an instance is created, but the object itself must implement freeze and freeze its own state. I'd like to add a `DeepFreeze` refinement to pakyow/support that will be used instead. `DeepFreeze` will call `deep_freeze` on any ivars defined on the object, then freeze itself. We should also be able to remove the `freeze` definitions on `Router` and `Route`.

**Comment by jphager2** [comment]
can this one be removed to? https://github.com/pakyow/pakyow/blob/environment/pakyow-support/lib/pakyow/support/configurable/config.rb#L37

**Comment by jphager2** [comment]
Looks like there will be a problem with freezing all ivars. A Pakyow::App has stores the Rack::Builder in an ivar, and that cant be frozen apparently.

**Comment by bryanp** [comment]
I think `unfreezable` makes sense, but maybe defined on the scope being refined? That would let `Pakyow::App` register the `@builder` ivar as being unfreezable.

**Comment by jphager2** [comment]
ok I made an update to the pull request.
