### ISSUE TITLE
Use Mutex in Definable / Configurable writes

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#254]

**Comment by jphager2** [comment]
Did you run into a problem with this?

**Comment by bryanp** [comment]
Did a problem lead me to create this issue? Or did I run into a problem implementing this?

**Comment by jphager2** [comment]
The former.

**Comment by bryanp** [comment]
No, just something I noticed. If two app instances are booting within separate threads in a process, it's possible for both to set some value on shared state (e.g. the environment). We want to guarantee that only one write can occur at a time.

**Comment by jphager2** [comment]
@bryanp wrote you on gitter
