### ISSUE TITLE
Update pakyow gem to use new config doc format

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#255]
Should match the config docs in pakyow/core.

**Comment by jphager2** [comment]
@bryanp like these here: https://github.com/pakyow/pakyow/blob/environment/pakyow-core/lib/pakyow/core/app.rb#L64?

**Comment by jphager2** [comment]
Are these the best place to put new config docs?

- https://github.com/pakyow/pakyow/blob/environment/pakyow-mailer/lib/pakyow/mailer/mailer.rb
- https://github.com/pakyow/pakyow/blob/environment/pakyow-presenter/lib/pakyow/presenter/presenter.rb
- https://github.com/pakyow/pakyow/blob/environment/pakyow-realtime/lib/pakyow/realtime/config.rb
- https://github.com/pakyow/pakyow/blob/environment/pakyow-ui/lib/pakyow/ui/base.rb

Or directly where they are defined?

- https://github.com/pakyow/pakyow/blob/environment/pakyow-mailer/lib/pakyow/mailer/config/mailer.rb
- https://github.com/pakyow/pakyow/blob/environment/pakyow-presenter/lib/pakyow/presenter/config/presenter.rb
- https://github.com/pakyow/pakyow/blob/environment/pakyow-realtime/lib/pakyow/realtime/config.rb
- https://github.com/pakyow/pakyow/blob/environment/pakyow-ui/lib/pakyow/ui/config.rb

**Comment by bryanp** [comment]
Yep, just like those that you linked to. Config options should be documented on the object that can be configured. In this case, the core `Pakyow` object (https://github.com/pakyow/pakyow/blob/environment/lib/pakyow/environment.rb#L99).

**Comment by jphager2** [comment]
So is this kind of what you are looking for? https://github.com/pakyow/pakyow/pull/261
