### ISSUE TITLE
Presentables should accept values and blocks

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#263]
State must be explicitly shared with a presenter. We've already introduced this pattern in #258 but it needs some improvements. Right now we only accept method names, like this:

```ruby
routes "/" do
  presentable :current_user

  def current_user
    ...
  end
end
```

```ruby
view "/" do
  present(current_user)
end
```

We want to expand presentable to accept a value:

```ruby
routes "/" do
  presentable Object.new
end
```

And also a block:

```ruby
routes "/" do
  presentable do
    ...
  end
end
```

The block would be called at the same point a method is called right now.

**Comment by rjclardy** [comment]
So that we can reference the values and block results from the presentation context we'll be passing a name as the first argument to `presentable`:

```ruby
routes "/" do
  post = Post.first

  # gives presentation context access to `post`
  presentable :post, post

  # gives presentation context access to `show_comments`
  presentable :show_comments do
    ...
  end
end
```
