### ISSUE TITLE
Thought for rejuvenation of project

### ISSUE THREAD

**Issue by ylluminate** [pakyow/pakyow#269]
Had a thought: it might be a novel and powerful idea to bring Pakyow over to [Amber](https://github.com/amberframework/amber). The speed is definitely there and the community is vibrant and forward moving and growing in momentum.

**Comment by bryanp** [comment]
Thanks for the suggestion, but my interest lies in driving the framework forward in Ruby. We've been steadily working on a series of refactors that will lead to 1.0. Take a look at the [environment branch](https://github.com/pakyow/pakyow/pull/210) if you're interested. Much more to come from this project, I can assure you.

**Comment by ylluminate** [comment]
Very interesting and thanks for the heads up. I think from a pure ruby standpoint that's fantastic, I have had the thought from a marketing standpoint there's a head of steam to take advantage of there if one were to be able to effectively abstract it where ruby and crystal wouldn't matter, which should be possible at some level.  Hmm.

**Comment by bryanp** [comment]
I like your line of thinking. There could be opportunities like this in the future. re: marketing, I have thoughts there as well. Email me if you want to talk further about it: bryan [AT] metabahn.com
