### ISSUE TITLE
 prototype is not a known command

### ISSUE THREAD

**Issue by westonganger** [pakyow/pakyow#298]
I stupidly forgot to `cd` into my new project after generating it. I then tried running `pakyow prototype` and got the following error:

```
 prototype is not a known command
```

It was super weird and I wondered why it would say that. Turns out its because I wasn't in the project folder. I am sure this applies to many commands other than prototype as well.

I would prefer a more truthful error description such as 

```
Cannot perform command `prototype: You are not within a pakyow project
```

**Comment by bryanp** [comment]
This is a great idea that seems to be fairly straight-forward to implement. It fits the spirit of the project too, since error messages should always be helpful and serve as teaching opportunities where appropriate. Will get this on the roadmap. Thanks for the suggestion @westonganger!
