### ISSUE TITLE
Docs show Right Arrow Icon instead of `-->`

### ISSUE THREAD

**Issue by westonganger** [pakyow/pakyow#299]
https://pakyow.com/docs/frontend/composition

For:

```
<!-- @container -->
<!-- @include messages -->
<!-- @container footer -->
```

 However the `-->` is being shown as a Right arrow icon

**Comment by bryanp** [comment]
There's a fix in place for this and it renders fine in Safari/Chrome on macOS, but seems to still appear as an arrow in Firefox. What browser / operating system do you see the issue @westonganger?

**Comment by westonganger** [comment]
Firefox

**Comment by bryanp** [comment]
This has been fixed.
