### ISSUE TITLE
Error with logger in production

### ISSUE THREAD

**Issue by iamvery** [pakyow/pakyow#65]
When going through the warmup exercise, I attempted to push the app to "prod" on Heroku and experienced an error. 

```
Puma caught this error: undefined method `write' for nil:NilClass (NoMethodError)
/app/vendor/bundle/ruby/2.1.0/gems/pakyow-core-0.9.1/pakyow-core/lib/core/middleware/logger.rb:47:in `block in <<'
/app/vendor/bundle/ruby/2.1.0/gems/pakyow-core-0.9.1/pakyow-core/lib/core/middleware/logger.rb:46:in `synchronize'
/app/vendor/bundle/ruby/2.1.0/gems/pakyow-core-0.9.1/pakyow-core/lib/core/middleware/logger.rb:46:in `<<'
/app/vendor/bundle/ruby/2.1.0/gems/pakyow-core-0.9.1/pakyow-core/lib/core/middleware/logger.rb:117:in `block in call'
/app/vendor/bundle/ruby/2.1.0/gems/pakyow-core-0.9.1/pakyow-core/lib/core/middleware/logger.rb:129:in `time'
/app/vendor/bundle/ruby/2.1.0/gems/pakyow-core-0.9.1/pakyow-core/lib/core/middleware/logger.rb:116:in `call'
/app/vendor/bundle/ruby/2.1.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.10.2/lib/puma/server.rb:492:in `handle_request'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.10.2/lib/puma/server.rb:363:in `process_client'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.10.2/lib/puma/server.rb:254:in `block in run'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.10.2/lib/puma/thread_pool.rb:101:in `call'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.10.2/lib/puma/thread_pool.rb:101:in `block in spawn_thread'
```

I believe this is because the value of [`io` here](https://github.com/pakyow/pakyow/blob/ee1f75731087dc7eddf698d9d9c151fe402175b9/pakyow-core/lib/core/base.rb#L50) can be `nil` which results in the `Logger` object being [initialized with `nil`](https://github.com/pakyow/pakyow/blob/ee1f75731087dc7eddf698d9d9c151fe402175b9/pakyow-core/lib/core/middleware/logger.rb#L36).

I was able to work around this by [configuring the app the log output in prod](https://github.com/iamvery/pakyow-warmup/commit/7f7ae865f77aa20d931166fd5684819f10457040). This makes sure the local [`logs` collection at least contains `$stdout`](https://github.com/pakyow/pakyow/blob/ee1f75731087dc7eddf698d9d9c151fe402175b9/pakyow-core/lib/core/base.rb#L48).

I did take a stab at isolating the issue with a spec and working on a fix, but the lib seems to be under tested (unless I'm missing them). To that end, I felt it was more in the owners jurisdiction to own the issue. Please do let me know if I can help!

**Comment by bryanp** [comment]
Yes, this was introduced in the latest 0.9.1 release. We have a fix in mind. Thanks for taking the time to report!
