### ISSUE TITLE
Server hangs when adding a view directory without an index.html file

### ISSUE THREAD

**Issue by hby** [pakyow/pakyow#69]
With Pakyow 0.9.1, do the following

mkdir test
cd test/
pakyow new thing
cd thing/
bundle install
bundle exec pakyow server

The server starts as it should. Now create a view directory and start the server.

cd app/views/
mkdir mail
cd ../..
bundle exec pakyow server

The server now hangs. Type ctrl-c and see a stack trace.

It will not hang if you put an index.html file in the new view directory.

**Comment by bryanp** [comment]
HA, I think this triggers some recursive view building. What happens is if a folder doesn't have an `index` view it looks one directory up. I imagine this doesn't stop at the root view directory.

**Comment by bryanp** [comment]
Yep, that was it. Fixed in this commit: https://github.com/pakyow/pakyow/commit/74c41aec8f20406e83c4f2a1869ebd62d454a96a
