### ISSUE TITLE
Load order in app/lib/**/*

### ISSUE THREAD

**Issue by jphager2** [pakyow/pakyow#72]
Maybe as a possible feature? Or maybe a bug?

Load order seems to matter in autoloading in lib and its subdirectories.

For example app/lib/models/guest_user.rb would be loaded before app/lib/models/user.rb, which means this would give you a NameError:

```
# in guest_user.rb
class GuestUser < User
end

# in user.rb
class User 
end
```

Right now, I guess the solution is just to require the file directly, but I think it would be nice if Pakyow could handle that.

**Comment by bryanp** [comment]
This has been considered, but you can't really get around the need for `require`. If I was writing unit tests for `GuestUser`, I wouldn't want to bootstrap the entire app. Rather, I would `require 'guest_user'` in my test. If `guest_user.rb` didn't contain the `require` statement I'd have to also require `user`, which seems like something the test shouldn't be concerned with. Now, you could both set the load order *and* require, but that seems redundant.

Any thoughts?

**Comment by jphager2** [comment]
You have a point for testing.  It just wasn't the behavior I expected because all the files are loaded anyway, but I wouldn't have thought to have considered the order, necessarily.

**Comment by bryanp** [comment]
Yep, makes sense. I'll be thinking about this!
