### ISSUE TITLE
Possible Bug in Reloading

### ISSUE THREAD

**Issue by jphager2** [pakyow/pakyow#73]
In app.rb, the load_app method always assigns a new loader

```
@loader = Loader.new
```

In order for the loading to work properly, I think it should be like this:

```
@loader ||= Loader.new
```

I would make a pull request, but it's only two characters.  Also, I'm not sure if using the load method is really the best, but I think I can let it slide because this is mostly developer's convenience.

A specific example where it gave me headaches is that activerecord validators are added into a class variable, and each time the class is loaded, the validators are appended to it.  That gave me the funny behavior of getting one more error each time I submitted an invalid form, depending on how many requests I had made to the server (i.e. how many times the model class had been loaded).

**Comment by bryanp** [comment]
I've seen that validator behavior before :)

You're saying that this change fixes that particular behavior? Or are you saying that using the `load` method causes the behavior? I think the latter, but wanted to confirm.

**Comment by jphager2** [comment]
The issue of only loading a file if it has been changed is fixed by keeping the loader in @loader (i.e. not creating a new loader for each call of the reload method, because in the loader there is an instance variable that keeps track of load times).

The issue with validators is not because even if you are only reloading the class when the file changes, it will still push more validators to the Model._validators hash.  But you can easily get around this by just calling the clear_validators! class method at the top of your model.  Then it works great. 

I think whether or not to use load (vs. I guess some wizardry with autoload and filename conventions) can be dealt with in the long run.  But I really think that the loader should be kept in the app instance because otherwise, the @times variable in the Loader class has no value.

**Comment by bryanp** [comment]
Cool, I follow now. Even though it's only two chars go ahead and submit a PR. You guy your name on it that way ;)
