### ISSUE TITLE
Possible bug in Presenter

### ISSUE THREAD

**Issue by jphager2** [pakyow/pakyow#75]
Okay, I've stumbled across something very strange, and I hope someone can help me out.

There seems to be a problem with creating a view context via ViewContext#scope for a data-scope that is nested within multiple partials.

Basically:

```
# index.html
<!-- @include partial_1 -->

# _partial_1.html
<!-- @include partial_2 -->

#_partial_2.html
<form data-scope="article" data-prop="action">
  #...
</div>
```

When I apply data to the scope in the routes like this:

```
view.scope(:article).apply({})
```

I get an undefined method "soft_copy" for nil error, which I have come to associate with "data-scope not found".

However, when I check this by creating the ViewCollection myself, I see that the scope is there:

```
coll = view.view.doc.scope(:article).inject(ViewCollection.new(:article)) do |coll, scope|
  view = View.from_doc(scope[:doc])
  view.scoped_as = :article
  coll << view
end
=> <Pakyow::Presenter::ViewCollection:0x007fa3f57bcca8 @views=[#<Pakyow::Presenter::View:0x007fa3f57bc8e8 @doc=#<Pakyow::Presenter::StringDoc:0x007fa3f57c2bd0 @structure=[...]>, @scoped_as=:article>], @scoped_as=:article>
```

Here is the crazy part. Just adding the code to get the ViewCollection in the routes makes the view work. (=p)  I have no idea why...

Happy to provide further information. Just fyi, I first noticed the problem using the 0.9.1 release, and then I installed from the github source, and the problem persisted.

So the two ways to get around this problem that I have discovered so far (as hot fixes) are:
1. Initialize a ViewCollection (using the code from View#scope)
2. Don't use deeply nested partials

**Comment by bryanp** [comment]
Wow, weird! I'll write a failing test case around this and go from there. Will report back :)

**Comment by bryanp** [comment]
@jphager2 Was able to reproduce; here's the [commit with the test](https://github.com/pakyow/pakyow/commit/c8569b0ba1177ede7a9a0df647c91e4503851c5b). Looking into what's causing the issue now.

**Comment by bryanp** [comment]
@jphager2 Okay, found the problem. It's fixed in [this commit](https://github.com/pakyow/pakyow/commit/c04e83e58e91ccf66b38796594fa912bb3528611). Thanks for reporting!

**Comment by jphager2** [comment]
Cool. Thanks
