### ISSUE TITLE
Dealing with ActiveRecord in pakyow-ui

### ISSUE THREAD

**Issue by jphager2** [pakyow/pakyow#76]
Two points.

## 1) So I came across an issue with ActiveRecord models.

In `UIView#mixin_bindings` the `#[]=` method is called for the object (in this case an ActiveRecord model).  I know that Pakyow requires the data objects to be accessible via `#[]`, which ActiveRecord models are, but you cannot set attributes this way if the attribute does not exist.

Example:

```
# ActiveRecord Migration for Article
class CreateArticles < ActiveRecord::Migration
  create_table :articles do |t|
    t.text :body
  end
end

# In lib/bindings.rb
scope :article do
  binding :body do
    { content: bindable[:body] }
  end
  binding :html_body do
    { content: render_html(bindable[:body] }
  end
end
```

You will get an error when `UIView#mixin_bindings` is called because there is no attribute in the Article model called `:html_body`.

## 2) Calling Mutable actions via `Mutable#method_missing` does not return the result of the mutable block.

This is probably not a bug, but I would argue that actions should return normally.  I think that this would be the expected behavior, and would be very helpful for control logic.

Example:

```
# Mutable
Pakyow::App.mutable :article do
  model Article
  
  action :create do |data|
    Article.create(object)
  end
 
  query :all do
    Article.all
  end
end

# Mutators
Pakyow::App.mutators :article do
  mutator :list do |view, articles|
    view.apply(articles)
  end
end

# Routes
restful :articles, '/articles' do
  list do
    view.scope(:article).mutate(:list, with: data(:articles).all).subscribe
  end
  new do
    view.scope(:article).with do |view|
      view.bind(@article || Article.new)
      handle_errors(view)
    end
  end

  create do
    @article = data(:article).create(params[:article])
    if @article.valid? && @article.persisted?
      redirect router.group(:article).path(:list)
    else
      @errors = @article.errors
      reroute router.group(:article).path(:new), :get
    end  
  end
end
```

## Proposed Fixes
1) Require datum passed to mutate respond to `#to_hash`, and then map that to the array in `UIView#mixin_bindings` instead of the altered datum.

2) Return the response of the block call in `Mutable#method_missing`

See this branch:
https://github.com/jphager2/pakyow/tree/issue-76

**Comment by jphager2** [comment]
I also just saw that there is a method called hashify in UIView. But it doesn't look like it can be used in this case (in its current form at least).

**Comment by bryanp** [comment]
For 1, we'll likely want to convert to a Hash like you're suggesting. The only thing to keep in mind here is that the object passed to the Binder needs to be the original object, not the Hash. But yeah, ultimately the data + bindings is converted into a Hash so I think it's fine to do that here.

For 2, I completely agree. That's the right way for it to work.

**Comment by jphager2** [comment]
Okay, made a pull request.

**Comment by bryanp** [comment]
Merged :)
