### ISSUE TITLE
Evaluate binding values that are procs

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#78]
Currently, binding code like that found below isn't compiled into proper ui instructions.

```ruby
binding :some_binding do
  { class: lambda { |c| c.ensure(:foo) } }
end
```

I think we can do this when mixing in bindings during a ui mutation. So, binding values that are props would be evaluated in a `UIAttrs` object, building up the proper instructions.

**Comment by bryanp** [comment]
@jphager2 are you interested in looking at this? I'll jump on it if not :)

**Comment by jphager2** [comment]
You bet. I've made a stab at it already. Maybe you could check it out and let me know if I am going in the right direction. https://github.com/jphager2/pakyow/tree/issue-78

**Comment by bryanp** [comment]
Mind opening a PR? (you can mark it WIP)

**Comment by jphager2** [comment]
ok will do.

**Comment by bryanp** [comment]
@jphager2 Here's a PR I made based on the conversation here and in your related PR: https://github.com/pakyow/pakyow/pull/87

Working on the JS side now to see if it'll work as clean as I think it will.

**Comment by bryanp** [comment]
@jphager2 Here's the PR for the JS side: https://github.com/pakyow/pakyow-js/pull/3

Ended up being fairly clean; thoughts before I merge all this?

**Comment by jphager2** [comment]
Hey. Looks good from my side and much cleaner, as you said. I thinks its
cool that you extracted ui_instructable. Just one question. Is there a
practical difference between ensure and insert? I saw that you specifcally
added #<< to ui_attrs. I guess that the only thing is to make sure the
documentation for bindings is specific enough that there is no confusion.

Looking forward to testing it!

**Comment by bryanp** [comment]
Yep `insert` will blindly add the value, `ensure` won't add it if it's already present.

Merging shortly!
