### ISSUE TITLE
Provide a helpful error message when transforming a non-existent scope.

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#79]
Currently all we get is this lousy default error message:

```ruby
undefined method soft_copy for nil:NilClass
```

**Comment by jphager2** [comment]
Also did some preliminary work on this, but ran into problems (https://github.com/jphager2/pakyow/tree/issue-79).  I thought the best idea would be to inject a null object into a view collection when the scope method would return an empty collection, that way a method later down the line could raise the proper error. Bit there are quite a few cases to consider within the application code.

**Comment by bryanp** [comment]
Mind opening a PR for this one too?

**Comment by bryanp** [comment]
@jphager2 Left a [comment](https://github.com/pakyow/pakyow/pull/85#issuecomment-118627925). This is one of the last things for the 0.10 release; let me know your thoughts when you can :-)

**Comment by bryanp** [comment]
Decided instead to just make it a no-op like other transformations on empty view collections (fixed with this commit: https://github.com/pakyow/pakyow/commit/87747e28bda598bd473444bd3c128c8eda1bc564). Long term we'd like to raise exceptions when attempting to transform an empty collection, which is captured in this issue: https://github.com/pakyow/pakyow/issues/88
