### ISSUE TITLE
Defining bindings in parts; let view decide what parts to use.

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#82]
A pattern I've seen in Pakyow apps is something like this:

```ruby
binding :show_link do
  { href: '...', content: '...' }
end

binding :show_href do
  { href: '...' }
end
```

You end up duplicating a binding simply because you only want part of it in the view. There are two parts to the feature I am proposing to fix this. First is to define bindings in parts:

```ruby
binding :show_link do
  part :href do
    '...'
  end

  part :content do
    '...'
  end
end
```

The current syntax would still work, but I feel that defining parts is more intuitive.

---

Secondly, I'd like to empower the designer to decide what parts to use from the view:

```html
<!-- defaults to all parts -->
<a data-prop="show_link" />

<!-- only use the href -->
<a data-prop="show_link" data-parts="href" />

<!-- exclude a single part -->
<a data-prop="show_link" data-parts-exclude="content" />
```

**Comment by jphager2** [comment]
Hi there! Could you exclude multiple parts? Does the separator matter?

**Comment by bryanp** [comment]
Hi @jphager2! Yep I was thinking it would follow the `class` attribute style:

```ruby
data-parts-exclude="content href"
```

**Comment by jphager2** [comment]
Ah, cool. That makes sense.

**Comment by jphager2** [comment]
Just thinking about it a bit more, if you use the `part` method, I suppose you couldn't also use a hash like:

```
binding :post do
  part :href do
  end
  { content: "foo" }
end
```

So if you want to use `part` it's all or nothing. Might that get a little verbose and unwieldy?

I imagine that `data-part` can work by just getting the binding and selecting the keys in the binding hash that are given (or not excluded, default being all included).  

I guess I am just having a hard time imagining this working as a convenience and not as a complete change of earlier syntax. But maybe I still haven't fully internalized everything, so let me know if I am off base.

**Comment by bryanp** [comment]
I'd really like to push people away from returning a `Hash`. It's a bit clunky and unintuitive IMO.

Agree though that typing `part` out a million times might not be ideal. Is there something in-between? We could do something like this:

```ruby
binding :post do
  href do
    ...
  end
end
```
