### ISSUE TITLE
Make it easier to set up forms.

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#96]
Say your view is a form for a particular scope:

```html
<form data-scope="foo">
</form>
```

Setting it up is currently very non-obvious. Here's how you'd do it for `create`:

```ruby
view.scope(:foo).bind(Foo.new)
```

And here it is for `update`:

```ruby
view.scope(:foo).bind(Foo.find(1))
```

The logic essentially looks for an `id` value on the object being bound, and sets up the form for creation or updating the datum. I'd like this to be more explicit. Currently thinking.

**Comment by jphager2** [comment]
Just throwing out an idea (feel free to shoot it down), but what about something like:

```ruby
view.form(:foo).new(Foo.new)

view.form(:foo).update(Foo.find(1))
```

Where `#form` could just be an alias for `#scope` and `#new`/`#update` could be the more explicit part of the api.

**Comment by bryanp** [comment]
I actually really like this. Only tweak I would make is change `form(:foo).new` to `form(:new).create)`. Great suggestion @jphager2!
